### PR TITLE
Changes made for Campus Manager accessibility audit

### PR DESCRIPTION
**Pull request by chrisperk**
hey Kevin, I made the following changes to Campus Manager for accessibility:

-added alt tag to nav logo
-changed text colors and background colors to pass contrast checks
-added title tags to some usercard link elements to signal purpose of link
-added text that user sees to phone and address usercard link elements to give meaning to phone number and ZIP number  ( * i tried using title and alt tags here but the test did not pass with them. adding the 'Phone: ' and 'ZIP: ' text that rendered for the user made the checks pass, but seems unnecessary, there is probably a better fix for this one that i'll continue to investigate)
-added aria-hidden tags to donut charts
-edited input id and label for tag so that the label properly pointed to the element

### CODE REVIEW

**Comment by chrisperk** [comment]
@kevincolten changes made in round 2:

-changed lang and title metadata for index.pug and layout.pug views
-changed yellow grade text to gold for contrast check
-added span class hidden to zip and phone text on usercard links

**need to find and edit metadata iframe (generated by google api script?) that is causing remaining fail on accessibility audit

**Comment by kevincolten** [comment]
This is great stuff! I fixed the tests so we can run them before merging. To bring them in, you need to run `git pull upstream develop` and then `git push origin accessibility` to watch them on circleci. Also, try running them locally with `npm run test` to make sure we have that set up correctly, as that'll be the next few tickets. More tests!

**Comment by chrisperk** [comment]
@kevincolten cool! i've pulled from upstream and run the updated tests, i have items 2 passing and 5 failing. should the next step to be working on figuring out what is triggering those 5 fails so that i can figure out what i need to fix so they pass?

**Comment by kevincolten** [comment]
Yep, you can see [here](https://circleci.com/gh/AustinCodingAcademy/aca-campus/223?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) that the tests are failing because whenever the tests were written, certain elements were targeted using style classes, which is generally a bad idea because classes and styles change. Go through the tests and figure out what element they are trying to reference, and add a `data-test="something-descriptive"` tag to those elements and update the tests.

**Comment by chrisperk** [comment]
@kevincolten 

hey i've been looking at these tests all day and can't get them to pass, i tried using the `data-test="something-descriptive"` tags as well as creating labels for the teal buttons that open the modals but may not have used them correctly. i did notice all the fails are coming from elements in modals. it seems that on the 'Create Location' tests, the test on the #users elements are passing but those in the #locations, #terms, and #courses ones are failing. i also noticed that the input info from the 'Make Course' test seems to be being entered into the stripe checkout input fields, so it seems like there i some disconnect when testing modals.

i searched for more info about data-test tags and found some information about the data-* class but not sure if i am using it correctly and also some info about using the xpath locator instead of a css locator but was not sure if that is the right rabbit hole to go down. 

example of how i've tried using data-test tag:

`<a data-test="locations-test" className="waves-effect waves-teal btn modal-trigger" onClick={this.newLocationModal}><i className="material-icons left">add</i> location</a>`

^^snippet of element code

`.click('a[data-test="locations-test"]')
    .pause(500)`

^^snippet of test code

**Comment by kevincolten** [comment]
I submitted a pull request against this pull request. Check it out and see if that fixes your issue. https://github.com/chrisperk/aca-campus/pull/1

**Comment by chrisperk** [comment]
@kevincolten 

hey i was able to merge that pull request and pull it into my local file, but i am still getting fails on those same 5 items. are those tests passing on your node?

**Comment by kevincolten** [comment]
Yeah, are you running `npm run test` or `npm run gulp test`?

**Comment by chrisperk** [comment]
dang i had been using `npm run test` but just tried `npm run gulp test` and still came up with those 5 fails. i must have merged incorrectly, but it looks like the diffs listed in the pull request are reflected on the files in my atom editor.  i tried running `npm install` to make sure i had all dependencies and then ran both tests again but still got those fails.

when i'm watching the tests run in the generated web browser, the browser never moves off the #users page on my test runs. it's like it can't find the #locations #terms or #courses links to get to the pages to check those button and input elements.

**Comment by chrisperk** [comment]
oh shoot i didnt see `npm test` let me try that

**Comment by kevincolten** [comment]
ok, this is working for more, I'm going to merge and see if it is just an environment issue. If so we can take a look at it next time you are at CF

**Comment by chrisperk** [comment]
Ok cool, thank you for your help working through this Kevin!! 

Yes I will try to drop by CF Monday or Tuesday to look at these tests on my machine and to see what Campus Manager project I may be able to help look at next.

Thanks again!

**Pull request merged**
