### PR TITLE
Auto-increase IDN when adding new user

### LINKED ISSUE #80: "idn" number not incrementing
When a new user is created, the idn is supposed to be incremented

### PR DESCRIPTION
**Pull request by nickdunn2**
resolves #80 

Only changed one line of code in UserController's create() method.

Just needed a +1 for user.idn = users[0].idn + 1;

### CODE REVIEW

**Comment by mistakevin** [comment]
Also look [here](https://github.com/AustinCodingAcademy/aca-campus/blob/master/routes/index.js#L47) if you haven't already. hen we create that first user, they need an idn (probably 1)

**Comment by nickdunn2** [comment]
Ah yes, I see. So regarding the /register route, will the only person hitting that be the initial user (so their IDN should always just be 1 and can be hard-coded in, like below), and then they'll subsequently add users through the interface? Or will multiple people be hitting that /register route, which would mean we have to first check to see if there's any users before assigning them either 1 or the next highest number?

Sorry, still trying to get a feel for the desired flow of this app.

screen shot 2016-06-24 at 9 47 58 am

**Comment by mistakevin** [comment]
Hey good find. You can probably move `is_client` into there as well

**Comment by mistakevin** [comment]
LGTM

Is this still considered "in progress"?

**Comment by joequery** [comment]
@nickdunn2 Most of the time when creating a database entry through an ORM, you let the database take care of the auto-incrementing. You'd specify all the required attributes minus the id and look for the id created for you in the response. When you attempt to manually specify an auto incrementing id, you may run into race conditions that eventually lead to id conflicts.

But this platform may be different and may force you to specify the id ahead of time. My 2cents.

**Comment by nickdunn2** [comment]
Awesome, thanks for the input @joequery! I'm still pretty unfamiliar with mongo compared to sql (where there's easy "auto-increment" options on a field. But I made changes to the userSchema in UserModel.js to sort of hack together the same concept (when combined with the user.idn = users[0].idn + 1; in UserController).

screen shot 2016-06-24 at 2 50 43 pm

I did find [this as an auto-increment option](https://www.npmjs.com/package/mongoose-auto-increment) for fields with mongoose, but it seems kinda like overkill.

As of now the first user will be given an idn of 1, the Model makes sure the idn is both required and unique, and it will auto-increment to the next highest number, even if lower numbers have subsequently been deleted, much like a standard id field (i.e., if users 1-5 have been created, user 2 is deleted, the next new user will be given an idn of 6, not 2.)

**Comment by mistakevin** [comment]
@joequery We are not using the Mongo assigned ObjectIds, but instead, our own IDN which is more human readable (in case a student ever just wants to type it from memory instead of scanning). They aren't the Primary Keys like in a Relational Database

**Pull request merged**
